import "../styles/globals.css";
import Script from "next/script";
import Providers from "@components/Providers";
import { Footer, Navbar } from "@components";
import { NFTProvider } from "@context/NFTContext";

export const metadata = {
  title: "NFT Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="dark:bg-nft-dark bg-white">
        <NFTProvider>
          <Providers>
            <Navbar />
            <div className="pt-65">{children}</div>
            <Footer />
            <Script
              src="https://kit.fontawesome.com/32562d9af9.js"
              crossorigin="anonymous"
            />
          </Providers>
        </NFTProvider>
      </body>
    </html>
  );
}
